### ISSUE TITLE
Update Tool question

### ISSUE THREAD

**Issue by mrbluecoat** [ashos/astos#159]
Cool project! A few newbie questions...

Your readme indicates

> AshOS needs little maintenance, as it has a built in fully automatic update tool that creates snapshots before updates and automatically checks if the system upgraded properly before deploying the new snapshot

Can you provide a bit more detail on that? Is that `ash upgrade ` or `ash upself`? I.E. is the update tool targeting the host AshOS or the snapshots/branches?

If I have a web server running on snapshot A, clone it and modify the website in snapshot B, then make snapshot B current, will external users see the new website? 

Is there automatic rollback if snapshot B fails to run?

Or is AshOS just meant for local development and fast desktop switching?

**Comment by ochibani** [comment]
- ash upgrade for snapshots upgrade and ash upself for ash self update.
- snapshot changes don't affect current running system unless you make ash deploy.
- Yes, there is a rollback if B fails to run.

**Comment by mrbluecoat** [comment]
Got it, thanks
