### ISSUE TITLE
Command 'debootstrap --arch amd64 --exclude=... sid /mnt http://ftp.debian.org/debian' returned non-zero exit status 1

### ISSUE THREAD

**Issue by apoordev** [ashos/astos#166]
While trying to install ashos for debian I keep running into this issue with debootstrap. If I run the full debootstrap command outside of the python script it works fine and is able to finish. But running it with the python script fails with the other mounts to /mnt.

I tried an older hybrid install iso (12.6) and I will continue to tinker to try and fix it.

Also the debian_live.sh prep script seems to fail with 
```sh
src/prep/debian_live.sh: 11: Syntax error: "(" unexpected (expecting "}")
```
I was able to fix this by just changing the `()` to `""` for `prep_packages=` in line 11

**Comment by i2** [comment]
I'll add this typo fix in my local fork and will push the change with a bunch of other features/fixes. Thank you!
